# This file created by conda-build 26.1.0
# meta.yaml template originally from:
# /home/task_177254812424319/xz-feedstock/recipe, last modified Tue Mar  3 14:31:59 2026
# ------------------------------------------------

package:
  name: xz
  version: 5.8.2
source:
  url: https://github.com/tukaani-project/xz/releases/download/v5.8.2/xz-5.8.2.tar.gz
  sha256: ce09c50a5962786b83e5da389c90dd2c15ecd0980a258dd01f70f9e7ce58a8f1
build:
  number: '0'
  run_exports:
    - xz >=5.8.2,<6.0a0
  string: h448239c_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - binutils_impl_linux-64 2.44 h4b9a079_2
    - binutils_linux-64 2.44 hc03a8fd_2
    - cmake-no-system 3.25.3 h6a678d5_0
    - gcc_impl_linux-64 14.3.0 h4943218_4
    - gcc_linux-64 14.3.0 hda73cce_12
    - kernel-headers_linux-64 4.18.0 h3108a97_1
    - ld_impl_linux-64 2.44 h153f514_2
    - libgcc 15.2.0 h69a1729_7
    - libgcc-devel_linux-64 14.3.0 he7458c1_104
    - libgcc-ng 15.2.0 h166f726_7
    - libgomp 15.2.0 h4751f2c_7
    - libsanitizer 14.3.0 hd4faa28_4
    - libstdcxx 15.2.0 h39759b7_7
    - libstdcxx-ng 15.2.0 hc03a8fd_7
    - ninja-base 1.13.1 h0f57076_0
    - sysroot_linux-64 2.28 h3108a97_1
    - tzdata 2025c he532380_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc 15.2.0 h69a1729_7
    - libgomp 15.2.0 h4751f2c_7
  run:
    - __glibc >=2.28,<3.0.a0
    - libgcc >=14
test:
  requires:
    - pkg-config
  commands:
    - xz --help
    - unxz --help
    - lzma --help
    - test -f ${PREFIX}/include/lzma.h
    - test -f ${PREFIX}/lib/cmake/liblzma/liblzma-config.cmake
    - test -f ${PREFIX}/lib/pkgconfig/liblzma.pc
    - test -f `pkg-config --variable=libdir --dont-define-prefix liblzma`/liblzma${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/liblzma.a
    - test -f ${PREFIX}/lib/liblzma${SHLIB_EXT}
    - test -f ${PREFIX}/lib/liblzma${SHLIB_EXT}.5
    - test -f ${PREFIX}/lib/liblzma${SHLIB_EXT}.5.8.2
about:
  home: https://tukaani.org/xz/
  license: LGPL-2.1-or-later and GPL-2.0-or-later and 0BSD
  license_file: COPYING
  license_family: GPL2
  summary: Data compression software with high compression ratio
  description: 'XZ Utils is free general-purpose data compression software with a
    high

    compression ratio. XZ Utils were written for POSIX-like systems, but also

    work on some not-so-POSIX systems.

    '
  doc_url: https://tukaani.org/xz/#_documentation
  dev_url: https://github.com/tukaani-project/xz
extra:
  recipe-maintainers:
    - mingwandroid
    - msarahan
    - nehaljwani
    - ocefpaf
    - scopatz
  final: true
  copy_test_source_files: true
  remote_url: https://github.com/AnacondaRecipes/xz-feedstock
  sha: 4783e2f43c7a92fb112ceb569d162fa290780d80
  task_id: NMJPrbJgTIWKXqQPQ93B2Q
  task_run_id: '0'
  pbp_graph_uuid: 59a56d01-5092-4d3b-b4dd-0a1f17128357
