# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176402097663695/python_abi-feedstock/recipe, last modified Mon Nov 24 21:49:54 2025
# ------------------------------------------------

package:
  name: python_abi
  version: '3.14'
build:
  number: '2'
  string: 2_cp314
requirements:
  build: []
  run: []
  run_constrained:
    - python 3.14.* *_cp314
test:
  commands:
    - echo "hello"
about:
  description: Metapackage to select python implementation
  dev_url: https://github.com/conda-forge/python_abi-feedstock
  doc_url: https://github.com/conda-forge/python_abi-feedstock
  home: https://github.com/conda-forge/python_abi-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Metapackage to select python implementation
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - chrisburr
    - isuruf
